# name: build and deploy on push to vercel with Datasette

# on:
#   push:
#     branches:
#       - main
#   # repository_dispatch:
#   # schedule:
#   #   - cron:  '0 0,12 * * *'

# jobs:
#   scheduled:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#       name: Check out repo
#     - name: Set up Python
#       uses: actions/setup-python@v1
#       with:
#         python-version: 3.9
#     - uses: actions/cache@v2
#       name: Configure pip caching
#       with:
#         path: ~/.cache/pip
#         key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
#         restore-keys: |
#           ${{ runner.os }}-pip-
#     # - uses: actions/cache@v2
#     #   with:
#     #     path: ~/.npm
#     #     key: ${{ runner.os }}-node-
#     #     restore-keys: |
#     #       ${{ runner.os }}-node-
#     - name: Install Python dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt
#     # - name: Setup Node.js
#     #   uses: actions/setup-node@v1
#     #   with:
#     #     node-version: '12.x'
#     - name: Deploy Datasette using Vercel
#       env:
#         NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
#       run: |-
#         datasette publish vercel esb.db \
#           --token $NOW_TOKEN \
#           --install datasette-graphql \
#           --install datasette-vega \
#           --project "esb-smart-meter"